tabelas = {}

tabelas['campeonato'] = (
"CREATE TABLE IF NOT EXISTS `campeonato` ("
" `id_campeonato` INT NOT NULL AUTO_INCREMENT,"
" `idjogo` INT NOT NULL,"
" `nome_campeonato` varchar(100) NOT NULL,"
" `partida` varchar(150) NOT NULL,"
" `data_hora` varchar(100) NOT NULL,"    
" PRIMARY KEY (`id_campeonato`)"
") ENGINE=InnoDB")

tabelas['jogos'] = (
"CREATE TABLE IF NOT EXISTS `jogos` ("
# " `id_partida` INT NOT NULL AUTO_INCREMENT,"
" `casa` float(4,2) NOT NULL,"    
" `fora` float(4,2) NOT NULL,"  
" `empate` float(4,2) NOT NULL,"      
" `casa_empate` float(4,2) NOT NULL,"    
" `casa_fora` float(4,2) NOT NULL,"  
" `empate_fora` float(4,2) NOT NULL," 
" `ambas_marcam` float(4,2) NOT NULL,"    
" `apenas_um_marca` float(4,2) NOT NULL,"    
" `ambas_marcam_2t_sim` float(4,2) NOT NULL,"  
" `ambas_marcam_2t_nao` float(4,2) NOT NULL,"  
" `ambas_marcam_1t_sim` float(4,2) NOT NULL," 
" `ambas_marcam_1t_nao` float(4,2) NOT NULL,"    
" `ambas_m_casa_ganha` float(4,2) NOT NULL,"    
" `ambas_nao_m_casa_ganha` float(4,2) NOT NULL,"    
" `ambas_m_fora_ganha` float(4,2) NOT NULL,"  
" `ambas_nao_m_fora_ganha` float(4,2) NOT NULL,"  
" `ambas_m_empatam` float(4,2) NOT NULL," 
" `ambas_nao_m_empatam` float(4,2) NOT NULL,"
" `jogo_acima_2.5` float(4,2) NOT NULL,"    
" `jogo_abaixo_2.5` float(4,2) NOT NULL,"    
" `jogo_abaixo_0.5` float(4,2) NOT NULL,"  
" `jogo_abaixo_1.5` float(4,2) NOT NULL,"  
" `jogo_acima_1.5` float(4,2) NOT NULL," 
" `jogo_acima_3.5` float(4,2) NOT NULL,"
" `casa_casa` float(4,2) NOT NULL,"    
" `casa_empate` float(4,2) NOT NULL,"    
" `casa_fora` float(4,2) NOT NULL,"  
" `empate_casa` float(4,2) NOT NULL,"  
" `empate_empate` float(4,2) NOT NULL," 
" `empate_fora` float(4,2) NOT NULL," 
" `fora_casa` float(4,2) NOT NULL,"    
" `fora_empate` float(4,2) NOT NULL,"    
" `fora_fora` float(4,2) NOT NULL,"  
#
" `casa_casa` float(4,2) NOT NULL,"    
" `casa_empate` float(4,2) NOT NULL,"    
" `casa_fora` float(4,2) NOT NULL,"  
" `empate_casa` float(4,2) NOT NULL,"  
" `empate_empate` float(4,2) NOT NULL," 
" `empate_fora` float(4,2) NOT NULL," 
" `fora_casa` float(4,2) NOT NULL,"    
" `fora_empate` float(4,2) NOT NULL,"    
" `fora_fora` float(4,2) NOT NULL," 
"  `id_jogo` INT NOT NULL,"
"  CONSTRAINT FK_CampeonatoJogo FOREIGN KEY (`id_jogo`),"
"  REFERENCES campeonato(`idjogo`)"
") ENGINE=InnoDB")